name: Node.js Bot

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm install
        
    - name: Run Bot
      env:
        # هنا نربط الـ Secrets الموجودة في إعدادات GitHub بالمتغيرات
        U_MAIL: ${{ secrets.U_MAIL }}
        U_PASS: ${{ secrets.U_PASS }}
      run: npm start

